.\" Manpage for ESMON.
.\" Contact Li Xi <lixi@ddn.com> to correct errors or typos.
.TH esmon_install 1 "16 Augest 2017" "2.0" "esmon_install man page"
.SH NAME
esmon_install \- Install Exascaler Monitoring
.SH SYNOPSIS
esmon_install [ options ]
.SH DESCRIPTION
ESMON(Exascaler Monitoring) is a monitoring system for DDN Exascaler.

.SH BUGS
No known bugs.
.SH AUTHOR
Li Xi <lixi@ddn.com>
