#!/usr/bin/python3 -u
# Copyright (c) 2017 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Install Exascaler monitoring system
"""
from pyesmon import esmon_install

if __name__ == "__main__":
    esmon_install.main()
