#!/usr/bin/python3 -u
# Copyright (c) 2017 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Test Exascaler monitoring system
"""
from pyesmon import esmon_test

if __name__ == "__main__":
    esmon_test.main()

