#!/usr/bin/python -u
# Copyright (c) 2017 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Build Exascaler monistoring system
"""
from pyesmon import esmon_build

if __name__ == "__main__":
    esmon_build.main()

