#!/usr/bin/python -u
# Copyright (c) 2017 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Test Exascaler monistoring system
"""
from pyesmon import esmon_test

if __name__ == "__main__":
    esmon_test.main()

